### ISSUE TITLE
Could you share the pre-trained model or result images for comparison?

### ISSUE THREAD

**Issue by shallow-dream-git** [erfect2020/ContextualDeblur#2]

**Comment by erfect2020** [comment]
Thank you for your attention to our work. The results are available on [Google Drive](https://drive.google.com/drive/folders/1-SH-xeGu8BfvYR0tKzBSdtVp4kNSMG2-?usp=sharing). As for the code, we need to review it and will release it as soon as possible.

**Comment by shallow-dream-git** [comment]
Thank you very much for your work. We will reference your paper in our future work！
